[tool.poetry]
name = "agent-service-toolkit"
version = "0.1.0"
description = "Full toolkit for running an AI agent service built with LangGraph, FastAPI and Streamlit."
authors = ["Joshua Carroll <carroll.joshk@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.12.3"
aiohttp = "~3.10.0"
arxiv = "~2.1.3"
duckduckgo-search = "~6.2.6"
fastapi = "<0.100.0"
langchain-core = "~0.2.26"
langchain-community = "~0.2.11"
langchain-openai = "~0.1.20"
langchain-groq = "~0.1.9"
langgraph = "~0.2.3"
langgraph-checkpoint = "~1.0.2"
langgraph-checkpoint-sqlite = "~1.0.0"
langsmith = "~0.1.96"
numexpr = "~2.10.1"
pydantic = "~1.10.17"
python-dotenv = "~1.0.1"
streamlit = "~1.37.0"
uvicorn = "~0.30.5"

[tool.poetry.dev-dependencies]
pytest = "*"
httpx = "0.26.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
